---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: admin@test.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chartmuseum.158.160.13.185.nip.io
  namespace: chartmuseum 
spec:
  dnsNames:
    - chartmuseum.158.160.13.185.nip.io
  secretName: chartmuseum-158-160-13-185-nip-io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer